# 1. unsqueeze_, expand

In [1]:
import torch
a = torch.Tensor([[0,1,2],[3,4,5],[6,7,8]])
print(a.size(), '\n', a)

torch.Size([3, 3]) 
 tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [23]:
a = a.unsqueeze_(-1)
print(a.size(), '\n', a)

torch.Size([3, 3, 1]) 
 tensor([[[0.],
         [1.],
         [2.]],

        [[3.],
         [4.],
         [5.]],

        [[6.],
         [7.],
         [8.]]])


In [24]:
a = a.expand(3,3,10)
print(a.size(), '\n', a)

torch.Size([3, 3, 10]) 
 tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]],

        [[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]]])


# 2. softmax param dim
- dim이 3차원 이상이면 이해하기 힘듦
- 해당 dim기준으로 sum=1로 만든다고 이해하면 됨
    - 2차원 row, col방향을 생각면 이해쉬움
    - 예컨대, 아래 예시에서 5는 column방향 dim; 4는 row방향 dim;

- 예시1

In [109]:
d = torch.rand(size=(2,3))
print(d.shape)
print(d)

torch.Size([2, 3])
tensor([[0.0766, 0.5221, 0.8039],
        [0.4790, 0.5274, 0.0297]])


In [113]:
print(d[0,:]) # 1.4027
print(d[1,:]) # 1.0361
print(d.sum(dim=1))
print(d.sum(dim=1).shape)

tensor([0.0766, 0.5221, 0.8039])
tensor([0.4790, 0.5274, 0.0297])
tensor([1.4027, 1.0361])
torch.Size([2])


- 예시2

In [41]:
softmax_layer = torch.nn.Softmax(dim=2)
data = torch.rand(3,3,2,4)
data

tensor([[[[0.2546, 0.6306, 0.5212, 0.6619],
          [0.8786, 0.8600, 0.1884, 0.4512]],

         [[0.4046, 0.1391, 0.5776, 0.0189],
          [0.3236, 0.1229, 0.4245, 0.8984]],

         [[0.8612, 0.9773, 0.7095, 0.8918],
          [0.7812, 0.6237, 0.2547, 0.7619]]],


        [[[0.0955, 0.8194, 0.1859, 0.6396],
          [0.3081, 0.6287, 0.9243, 0.8334]],

         [[0.8969, 0.0485, 0.0851, 0.0293],
          [0.5866, 0.2562, 0.5555, 0.3136]],

         [[0.5425, 0.3511, 0.0597, 0.7261],
          [0.7985, 0.3184, 0.9888, 0.4610]]],


        [[[0.5693, 0.5047, 0.3301, 0.0699],
          [0.3018, 0.6755, 0.2705, 0.8298]],

         [[0.1888, 0.4471, 0.9331, 0.0616],
          [0.3175, 0.9577, 0.7849, 0.2476]],

         [[0.2937, 0.0126, 0.6711, 0.0354],
          [0.8750, 0.9020, 0.5535, 0.6844]]]])

In [59]:
z = softmax_layer(data)
print(z.shape)
print(z)

torch.Size([3, 3, 2, 4])
tensor([[[[0.3489, 0.4429, 0.5824, 0.5525],
          [0.6511, 0.5571, 0.4176, 0.4475]],

         [[0.5202, 0.5041, 0.5382, 0.2933],
          [0.4798, 0.4959, 0.4618, 0.7067]],

         [[0.5200, 0.5875, 0.6118, 0.5324],
          [0.4800, 0.4125, 0.3882, 0.4676]]],


        [[[0.4471, 0.5475, 0.3234, 0.4517],
          [0.5529, 0.4525, 0.6766, 0.5483]],

         [[0.5770, 0.4483, 0.3845, 0.4294],
          [0.4230, 0.5517, 0.6155, 0.5706]],

         [[0.4364, 0.5082, 0.2831, 0.5659],
          [0.5636, 0.4918, 0.7169, 0.4341]]],


        [[[0.5665, 0.4574, 0.5149, 0.3187],
          [0.4335, 0.5426, 0.4851, 0.6813]],

         [[0.4679, 0.3750, 0.5370, 0.4536],
          [0.5321, 0.6250, 0.4630, 0.5464]],

         [[0.3586, 0.2912, 0.5294, 0.3432],
          [0.6414, 0.7088, 0.4706, 0.6568]]]])


In [62]:
# 2 dim의 idx 0 data
z[0,0,:,0]

tensor([0.3489, 0.6511])

In [61]:
z_sum = z.sum(dim=2, keepdims=False)
z_sum.shape # torch.Size([3, 3, 2, 4]) -> torch.Size([3, 3, 4])

torch.Size([3, 3, 4])

# 3. 3차 이상 tensor의 transpose
- dim params: shape에서 각 idx를 dim으로 생각하고 입력
    - eg. shape(2,3,4) <- dim 0==2, dim 1==3, dim 2==4

In [195]:
torch.manual_seed(99)
data = torch.randint(0, 10, size=(2,4,3))
print(data)

tensor([[[1, 9, 1],
         [0, 1, 8],
         [2, 8, 5],
         [0, 9, 5]],

        [[0, 9, 9],
         [3, 7, 8],
         [7, 3, 8],
         [5, 6, 3]]])


- 예시1

In [202]:
# (2,4,3) -> (2,3,4)
data_T = data.transpose(1,2)
print(data_T)
print('------------------------------transpose')
print(data[0, :, :])
print(data_T[0, :, :])

tensor([[[1, 0, 2, 0],
         [9, 1, 8, 9],
         [1, 8, 5, 5]],

        [[0, 3, 7, 5],
         [9, 7, 3, 6],
         [9, 8, 8, 3]]])
------------------------------transpose
tensor([[1, 9, 1],
        [0, 1, 8],
        [2, 8, 5],
        [0, 9, 5]])
tensor([[1, 0, 2, 0],
        [9, 1, 8, 9],
        [1, 8, 5, 5]])


- 예시2

In [203]:
# (2,4,3) -> (4,2,3)
data_T2 = data.transpose(0,1)
print(data_T2)
print('------------------------------transpose')
print(data[:,:,0])
print(data_T2[:,:,0])

tensor([[[1, 9, 1],
         [0, 9, 9]],

        [[0, 1, 8],
         [3, 7, 8]],

        [[2, 8, 5],
         [7, 3, 8]],

        [[0, 9, 5],
         [5, 6, 3]]])
------------------------------transpose
tensor([[1, 0, 2, 0],
        [0, 3, 7, 5]])
tensor([[1, 0],
        [0, 3],
        [2, 7],
        [0, 5]])


# 4. conv1d
- input data shape
    - bs, [n_seq, n_hidn]
- params
    - in_channels (int): Number of channels in the input image
    - out_channels (int): Number of channels produced by the convolution
    - kernel_size (int or tuple): Size of the convolving kernel

In [193]:
bs = 3; n_seq=5; d_hidn = 10;
data = torch.randn(bs, n_seq, d_hidn)  
conv1d = nn.Conv1d(in_channels=n_seq,\
                   out_channels=d_hidn,\
                   kernel_size=3)

# out shape: torch.Size([32, 7, 8])
out = conv1d(data)
print(out.size())
print(conv1d)

torch.Size([3, 10, 8])
Conv1d(5, 10, kernel_size=(3,), stride=(1,))
